kind: ReplicationController
apiVersion: v1
metadata:
  name: eventstore-cluster
spec:
  replicas: 3
  selector:
    name: eventstore-node
  template:
    metadata:
      labels:
        name: eventstore-node
    spec:
      containers:
      - name: eventstore-node
        image: dcr.mfb.io/eventstore
        ports:
        - containerPort: 2113
        - containerPort: 2112
        - containerPort: 1113
        - containerPort: 1112
        env:
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "3"
        - name: EVENTSTORE_CLUSTER_GOSSIP_PORT
          value: "2112"
        - name: EVENTSTORE_CLUSTER_DNS
          value: "eventstore-service.default.svc.cluster.local"
        - name: EVENTSTORE_INT_IP
          value: "0.0.0.0"
        - name: EVENTSTORE_EXT_IP
          value: "0.0.0.0"
        - name: EVENTSTORE_EVENTSTORE_EXT_HTTP_PREFIXES
          value: ~
        - name: EVENTSTORE_EVENTSTORE_INT_HTTP_PREFIXES
          value: ~
        volumeMounts:
        - mountPath: /var/lib/eventstore
          name: data
      volumes:
        - name: data
          emptyDir: {}
