kind: Service
apiVersion: v1
metadata:
  name: eventstore-lb
spec:
  type: LoadBalancer
  selector:
    app: eventstore-rc
  ports:
  - name: 'external-http'
    protocol: TCP
    port: 2114
    targetPort: 2114
    nodePort: 30061
  - name: 'external-tcp'
    protocol: TCP
    port: 1113
    targetPort: 1113
    nodePort: 30051
